name: Build and Deploy Development Build

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy development build
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_IP }}
          username: codeman
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd CodeManDev
            git checkout dev
            git pull
            ./deploy.sh