name: Build and Deploy Development Build

on:
  push:
    branches: [ dev ]

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build and deploy development build
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_IP }}
          username: codeman
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd CodeManDev
            git checkout dev
            git pull
            ./gradlew shadowjar
            ./gradlew docker
            ./gradlew dockerStop
            ./gradlew dockerRun
      
