name: Build and Deploy Production Build

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy production build
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_IP }}
          username: codeman
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd CodeManProd
            git checkout main
            git pull
            ./deploy.sh