name: Auto deployement on the production bot

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy production build
        uses: appleboy/ssh-action@master
        with: 
          host: 144.91.113.190
          username: codeman
          key: ${{ secrets.SSH_SECRET_KEY }}
          port: 22
          script: |
            cd CodeManProd
            git checkout main
            git pull
            ./gradlew shadowjar
            ./gradlew docker
            ./gradlew dockerStop
            ./gradlew dockerStart
